set vb t_vb=
set nobackup
set nowb
set noswapfile
set hidden
set ruler
set hlsearch
syntax enable
filetype indent plugin on
set encoding=utf-8
set expandtab
set shiftwidth=2
set tabstop=2
set backspace=indent,eol,start         " let backspace delete everything, not just inserted text
set incsearch                          " jump to search result while typing
language messages en_US
:let mapleader = ","

if has("gui_running")
  set guifont=Courier\ New:h10:cANSI
endif

let g:netrw_banner = 0                 " avoid useless netrw banner
let g:netrw_liststyle = 1              " add size and file info

set wildmode=longest,list,full         " (almost) Bash-style tab-completion
set wildmenu
set wildignore=*.o,*.class,*.exe,*.a,*.so,*.dll,*.pyc

set path=.,,C:/devsbb/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++

" Find tags file in current buffer's directory or any dir up the tree.
set tags=./tags;

" Move line up/down
nnoremap ê :m .+1<CR>==
nnoremap ë :m .-2<CR>==
nnoremap <Leader>s :update<CR>
nnoremap <Leader>w :bd<CR>
nnoremap <Leader>a :Ack<Space>
" Find word under cursor
nnoremap <Leader>A :Ack<Space><C-R><C-W> 
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>m :make<CR>
nnoremap <Leader>b :ls<CR>:b<Space>
nnoremap <Leader>e :Explore<CR>
nnoremap <Leader>t :CtrlPTag<CR>
" Navigate through quickfix list
nnoremap <C-j> :cn<CR>
nnoremap <C-k> :cp<CR>
nnoremap <C-l> :nohlsearch<CR><C-l>
" Next/previous buffer
nnoremap [b :bprevious<CR>
nnoremap ]b :bnext<CR>
" make * search for selected text in visual mode
vnoremap * y/\V<C-r>=escape(@",'/\')<CR><CR>


set makeprg=mingw32-make.exe
if executable('ag.exe')
  set runtimepath^=C:\devsbb\vim\bundle\ack.vim
  let g:ackprg = 'ag.exe --vimgrep'
endif

execute pathogen#infect()

" let g:ctrlp_custom_ignore = 'node_modules/\|\.git/'

