set noerrorbells
set vb t_vb=
set nobackup
set nowb
set noswapfile
set hidden
set ruler
set hlsearch
syntax enable
set encoding=utf-8
set expandtab
set shiftwidth=2
set tabstop=2
set cindent

:let mapleader = ","

if has("gui_running")
  set guifont=Consolas:h11:cANSI
endif

nnoremap ê :m .+1<CR>==
nnoremap ë :m .-2<CR>==
nnoremap <Leader>s :update<CR>
nnoremap <Leader>w :bd<CR>
nnoremap <Leader>g :vimgrep /
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>m :make<CR>
nnoremap <C-j> :cn<CR>
nnoremap <C-k> :cp<CR>
nnoremap <C-l> :nohlsearch<CR><C-l>

set runtimepath^=C:\devsbb\vim\bundle\ctrlp.vim
set makeprg=mingw32-make.exe
